# Generated by Django 5.1.6 on 2026-02-25 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('detected_food', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('raw_nutrition_data', models.JSONField(blank=True, default=dict)),
                ('user_notes', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'logged_at'], name='core_meallo_user_id_1b3d2a_idx'), models.Index(fields=['status'], name='core_meallo_status_3d6a16_idx')],
            },
        ),
    ]
